### ISSUE TITLE
ECP formatting 

### ISSUE THREAD

**Issue by DattaHub** [DattaHub/GL#8]
I am trying to format this paper following the ECP guidelines but the bibliography is giving errors. It's most likely due to the obsolete nature of ECP package on CTAN but could be other compatibility issues. 

[https://ctan.org/tex-archive/macros/latex/contrib/ejpecp](https://ctan.org/tex-archive/macros/latex/contrib/ejpecp)

@brandonwillard suggestions?

#formatting_issues

**Comment by brandonwillard** [comment]
After installing all `ejpecp`, its dependencies, and converting the title and bib settings to follow `ejpecp/sample.tex` (e.g. macros `\AUTHORS`, `\DOI`, etc.), it seems to compile.

There are still some (possibly unrelated) errors and/or warnings, but I'm looking into those now.

**Comment by brandonwillard** [comment]
I just created an [ecp-format branch](https://github.com/brandonwillard/GL/tree/ecp-format) on my forked repo.  In it, I added a `Makefile`, so you can just run `make gl-exp.pdf` or `make` to build the PDFs (they're output to a local `output` directory).

Otherwise, I wasn't sure which `.tex` file to use.  For sanity's sake, we should created separate branches dedicated to each journal format; that way, we can continue to work on the master LaTeX file in the master branch, then merge any of those changes into whichever journal-format branch needs them.  Basically, each journal-format branch only tracks changes relevant to journal formatting.

**Comment by DattaHub** [comment]
That's a very good idea. I am sure Biometrika and ECP are diametrically
opposite. Although once we move on from a journal, that formatting becomes
useless for that one paper. Maybe, create a journal formatting repo for the
regular venues?

JD

**Comment by brandonwillard** [comment]
Yeah, a repo with minimum working examples and a Docker image with the requisite LaTeX environment (i.e. texlive with all necessary packages installed) would be great.  We'll still need separate branches for each venue in any given paper's repo, though.
